### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by RFoe** [RFoe/Kelpa#1]
- [ ] Socket API HOOK
- [ ] Asynchronous encapsulation of Socket module
- [ ] IP address cluster encapsulation
- [ ] IOCP
